#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Vision, foam wall horizon gate, and target tracking configurations."""

from pathlib import Path

TARGET_VISION_ENABLED = True
TARGET_PREVIEW_ENABLED = True
TARGET_WINDOW_NAME = "RoboMaster Target Vision"

# Camera stream resolution
TARGET_CAMERA_RESOLUTION = "360p"

# Region of interest (normalized coordinates)
TARGET_ROI_X_MIN = 0.20
TARGET_ROI_X_MAX = 0.80
TARGET_ROI_Y_MIN = 0.16
TARGET_ROI_Y_MAX = 0.88

# ------------------------------------------------------------
# FOAM-WALL SPATIAL GATE
# ------------------------------------------------------------
TARGET_FOAM_GATE_ENABLED = True
TARGET_FOAM_FAIL_CLOSED = False

TARGET_FOAM_HSV_LOW = (0, 0, 115)
TARGET_FOAM_HSV_HIGH = (180, 48, 255)
TARGET_FOAM_OPEN_KERNEL = 3
TARGET_FOAM_CLOSE_KERNEL = 9

TARGET_FOAM_MIN_COMPONENT_AREA_PX = 1800
TARGET_FOAM_MIN_COMPONENT_WIDTH_PX = 35
TARGET_FOAM_MIN_COMPONENT_HEIGHT_PX = 35
TARGET_FOAM_COMPONENT_MIN_BOTTOM_FRAC = 0.42

TARGET_FOAM_PROFILE_MAX_INTERP_GAP_PX = 64
TARGET_FOAM_PROFILE_MEDIAN_RADIUS_PX = 7
TARGET_FOAM_PROFILE_SAMPLE_RADIUS_PX = 12
TARGET_FOAM_PROFILE_TTL_SEC = 0.55
TARGET_FOAM_MIN_ROI_COVERAGE = 0.12

TARGET_FOAM_CENTER_MARGIN_PX = 4
TARGET_FOAM_MIN_BBOX_BELOW_FRAC = 0.55

# ------------------------------------------------------------
# HSV TARGET RANGES & SHAPE FILTERS
# ------------------------------------------------------------
TARGET_HSV_RANGES = {
    "RED": [
        ((0, 95, 65), (11, 255, 255)),
        ((169, 95, 65), (180, 255, 255)),
    ],
    "YELLOW": [
        ((18, 100, 80), (38, 255, 255)),
    ],
    "GREEN": [
        ((38, 75, 55), (90, 255, 255)),
    ],
    "BLUE": [
        ((92, 85, 55), (138, 255, 255)),
    ],
}

TARGET_MIN_AREA_FRAC_ROI = 0.0018
TARGET_MAX_AREA_FRAC_ROI = 0.20

TARGET_MIN_SOLIDITY = 0.86
TARGET_RECT_MIN_FILL = 0.68
TARGET_RECT_MAX_CORNER_COS = 0.42
TARGET_CIRCLE_MIN_CIRCULARITY = 0.72
TARGET_CIRCLE_ASPECT_MIN = 0.70
TARGET_CIRCLE_ASPECT_MAX = 1.42
TARGET_POLY_EPS_FRAC = 0.035
TARGET_BORDER_MARGIN_PX = 5

TARGET_SQUARE_ASPECT_MIN = 0.78
TARGET_SQUARE_ASPECT_MAX = 1.28
TARGET_RECT_ASPECT_MIN = 1.28

TARGET_HISTORY_SEC = 0.90
TARGET_CONFIRM_FRAMES = 3
TARGET_CONFIRM_MAX_CENTER_STD = 0.045
TARGET_CONFIRM_MAX_AREA_CV = 0.38

TARGET_MIN_CONFIDENCE = 0.50
TARGET_SAVE_CONFIDENCE = 0.60
TARGET_SAMPLE_FRAMES = 10
TARGET_VERIFY_FRAMES = 3
TARGET_HOLD_MAX_SEC = 3.0
TARGET_HOLD_MAX_WINDOWS = 3

TARGET_SAMPLE_WINDOW_TIMEOUT_SEC = 0.85
TARGET_SAMPLE_POLL_SEC = 0.015

# ------------------------------------------------------------
# TARGET SWEEP POSES
# ------------------------------------------------------------
TARGET_SWEEP_PITCH_NORMAL_DEG = -5.0
TARGET_SWEEP_PITCH_DIAGONAL_LOW_DEG = -15.0
TARGET_SWEEP_PITCH_DEEP_DEG = -22.5
TARGET_DIAGONAL_YAW_MIN_DEG = 25.0
TARGET_DIAGONAL_YAW_MAX_DEG = 65.0

TARGET_SWEEP_POSES = (
    (-82.0, TARGET_SWEEP_PITCH_NORMAL_DEG),
    (-82.0, TARGET_SWEEP_PITCH_DEEP_DEG),
    (-45.0, TARGET_SWEEP_PITCH_NORMAL_DEG),
    (-45.0, TARGET_SWEEP_PITCH_DIAGONAL_LOW_DEG),
    (  0.0, TARGET_SWEEP_PITCH_NORMAL_DEG),
    (  0.0, TARGET_SWEEP_PITCH_DEEP_DEG),
    (+45.0, TARGET_SWEEP_PITCH_NORMAL_DEG),
    (+45.0, TARGET_SWEEP_PITCH_DIAGONAL_LOW_DEG),
    (+82.0, TARGET_SWEEP_PITCH_NORMAL_DEG),
    (+82.0, TARGET_SWEEP_PITCH_DEEP_DEG),
)

TARGET_SWEEP_SETTLE_SEC = 0.07
TARGET_SWEEP_OBSERVE_SEC = 0.24
TARGET_SCAN_COOLDOWN_SEC = 0.80

TARGET_GLIMPSE_ENABLED = True
TARGET_GLIMPSE_LINGER_SEC = 0.38
TARGET_GLIMPSE_MIN_SCORE = 0.48
TARGET_GLIMPSE_BEARING_MERGE_DEG = 18.0
TARGET_GLIMPSE_MAX_PER_CELL = 8

# ------------------------------------------------------------
# RETURN-PASS RESCAN
# ------------------------------------------------------------
TARGET_RETURN_RESCAN_ENABLED = True
TARGET_DFS_BACKTRACK_RESCAN_ENABLED = True
TARGET_FAST_RETURN_RESCAN_ENABLED = True
TARGET_RETURN_RESCAN_GLIMPSES = True
TARGET_RETURN_RESCAN_LOCKED = True
TARGET_RETURN_RESCAN_MAX_ITEMS_PER_CELL = 5
TARGET_RETURN_RESCAN_OBSERVE_SEC = 0.30
TARGET_RETURN_RESCAN_LINGER_SEC = 0.32
TARGET_RETURN_RESCAN_YAW_OFFSETS_DEG = (0.0, -10.0, +10.0)
TARGET_FUSION_MAX_SAMPLES = 12

# ------------------------------------------------------------
# TARGET LOCK & DEDUPLICATION
# ------------------------------------------------------------
TARGET_LOCK_MAX_STEPS = 3
TARGET_LOCK_CENTER_TOL_X = 0.055
TARGET_LOCK_CENTER_TOL_Y = 0.070
TARGET_LOCK_HFOV_DEG = 80.0
TARGET_LOCK_VFOV_DEG = 48.0
TARGET_LOCK_MAX_YAW_STEP_DEG = 16.0
TARGET_LOCK_MAX_PITCH_STEP_DEG = 10.0
TARGET_LOCK_YAW_LIMIT_DEG = 88.0
TARGET_LOCK_PITCH_MIN_DEG = -25.0
TARGET_LOCK_PITCH_MAX_DEG = TARGET_SWEEP_PITCH_NORMAL_DEG
TARGET_LOCK_SETTLE_SEC = 0.10

TARGET_DEDUPE_GRID_DIST = 0.55
TARGET_DEDUPE_BEARING_DEG = 22.0
TARGET_DEDUPE_SAME_CELL_ONLY_IF_NO_RANGE = True

SDK_MARKER_ENABLED = True
SDK_MARKER_TTL_SEC = 0.55
SDK_MARKER_CONFIRM_FRAMES = 2

TARGET_LATEST_JSON = Path("maps") / "latest_targets.json"
